### ISSUE TITLE
Clarification about double enzymes digestion

### ISSUE THREAD

**Issue by Liukvr** [pgcbioinfo/rapyds#1]
Dear developers,

Thanks for this very usefull tool. I have a question regarding ddRAD restriction site calculation. The sites number (e.g #Frags after Digestion #Frags filtered) are calculated only considering those fragments digested by both the selected enzymes (one for each side)? Or they include also those fragments digested by the same enzyme at both side? 

Thanks in advance for your support,
Luca

**Comment by kadgabriel** [comment]
Hello Luca,

For both `#Frags after Digestion` and `#Frags filtered` in rapyds's ddRAD mode, we only considered the fragments digested by a combination of the two selected enzymes. Fragments which sticky ends are from the same enzyme are not included in the count.

Arielle

**Comment by Liukvr** [comment]
Hi Arielle,

Great! many thanks for the quick reply!

Best,
Luca
